version: "3"

services:
  front-end:
    build: front-end/
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_USER=${USER}
      - RABBITMQ_PASS=${PASS}
    # uncomment for development
    volumes:
      - "./front-end/app:/var/www/html"
#  messaging:
#    image: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=${USER}
#      - RABBITMQ_DEFAULT_PASS=${PASS}
#  back-end:
#    build: back-end/
#    environment:
#      - RABBITMQ_DEFAULT_USER=${USER}
#      - RABBITMQ_DEFAULT_PASS=${PASS}
# Can uncomment messaging and backend section once the rest of the backend code is done
  # db:
