version: "3"

services:
  front-end:
    build: front-end/
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_USER=${USER}
      - RABBITMQ_PASS=${PASS}
    # uncomment for development

  messaging:
   image: rabbitmq:3.8-management
   environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
  back-end:
    build: back-end/
    environment:
      - MSG_USER=${USER}
      - MSG_PASS=${PASS}
# Can uncomment messaging and backend section once the rest of the backend code is done
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: foods
      POSTGRES_USER: ${POSTGRES_USER_E}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_E}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" 

