version: "3"

services:
  front-end:
    build: front-end/
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    # uncomment for development

  messaging:
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "15672:15672"
  back-end:
    build: back-end/
    environment:
      - MSG_USER=${RABBITMQ_USER}
      - MSG_PASS=${RABBITMQ_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  # Can uncomment messaging and backend section once the rest of the backend code is done

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - .db-data:/var/lib/postgressql/data

volumes:
  db-data:
